### ISSUE TITLE
zusätzliche Infos

### ISSUE THREAD

**Issue by Gelbwichtel** [windundsterne/esp-kwb-mqttlogger#3]
Hi, weiß zwar nicht ob das hier der richtige Platz dafür ist, aber ich fang einfach mal an. 

1. client-Publish Anzeige in Fhem
Beim Arbeiten mit dem client.publish ist mir Folgendes aufgefallen:
Werden viele clientPublish-Befehle hintereinander abgesetzt, dann stimmt irgendwann in FHEM die Reihenfolge in der Anzeige nicht mehr. Um das herauszufinden hatte ich im Sketch jedes publish um einen Counter versehen und dieses dann mit ausgegeben. Wird dabei irgendein "Schwellwert" überschritten, scheint FHEM ev. einen weiteren Thread anzulegen, die dann asynchron in die gleiche Ausgabe arbeiten. z.B.
anstatt ... 1200456, 1200457, 1200458, 1200459 ... kam dann ...1200456, 1200458, 1200459, 1200457 ... raus. 
Hatte mich einiges an Nerven gekostet. Lösung dafür nicht gefunden, ausser die Datenmenge zu reduzieren.

2. EasyFire2 weitere Control / SenseDaten
    Aussentemperatur : (Sense) getval2(anData, 18, 2, 0.1, 1)
    Saugturbine: (Control)         getbit(anData, 9, 5)
    Drehung Saugschlauch links (Control): getbit(anData, 4, 3)
    Drehung Saugschlauch rechts (Control): getbit(anData, 4, 1)
    Position Saugschlauch 0,1,2,3 noch nicht entdeckt, aber eher nicht in den Control Daten

**Comment by windundsterne** [comment]
Cool, habs mal ins Wiki geschrieben, vielleicht hat ja jemand anderes noch was...
