### ISSUE TITLE
DivisionByZero error

### ISSUE THREAD

**Issue by Gelbwichtel** [windundsterne/esp-kwb-mqttlogger#4]
Hi, wenn du gelegentliche Abstürze hast könnte das daher kommen:

  if (Kessel.Hauptantriebtakt != 0 )
  {
     Kessel.Hauptantriebzeit += (oKessel.Hauptantrieb * (milli - timerHA)) / (oKessel.Hauptantriebtakt);
  }

sollte sein:   if (oKessel.Hauptantriebtakt != 0 )

**Comment by windundsterne** [comment]
Danke ist korrigiert
