### ISSUE TITLE
potentieller Absturz durch Speicherleck

### ISSUE THREAD

**Issue by Gelbwichtel** [windundsterne/esp-kwb-mqttlogger#5]
Die inttobin() Funktion allokiert Speicher, führt in Kombination mit einem sprintf(), wie du es zum Loggen benutzt hast, zu einem Speicherleck führt. Je öfter dieser Code dann durchlaufen wird, desto weniger Ram steht zur Verfügung und dann stürzt der Wemos mit Fehlern ab.

Ich verwende das jetzt z.B. in der Art:

char *o = inttobin(oa); sprintf(oCtrlBits,"%s",o); delete o;

**Comment by windundsterne** [comment]
uiii, das stimmt! Ist bei mir nicht aufgefallen, da ich die Binärausgaben, meinst nur zu Debuggingzwecken und nicht dauerhaft in Betrieb hab. Danke für den Hinweis. Werds in den Beispielcode übernehmen.
