### ISSUE TITLE
Hardware-Hilfe

### ISSUE THREAD

**Issue by marfel** [windundsterne/esp-kwb-mqttlogger#7]
Hallo Philip,

vielen Dank für dieses tolle Repo - wir haben hier eine Pelletfire Plus, die ich gerne auslesen und in meine Influx-Datenbank einpflegen will. Mit den Codeänderungen komme ich schon klar (glaube ich ;) aber bei der Hardware bin ich unsicher (da kein Elektroniker). Daher meine Fragen:

1. Wo finde ich typischerweise so einen RS485-Stecker in der Anlage? Im Steuerungsmodul?
2. Ich dachte bei RS485 muss alles an einem Strang hängen und am Ende ein Abschlusswiderstand - wie kann man da irgendwo noch ein Gerät in den Bus hängen, ohne die Kabel aufzuschneiden? Oder muss ich mir das mit dem Stecker so vorstellen, dass die Elektronik den Stecker überbrückt, wenn kein Gerät angeschlossen ist?
3. Mit MAX485 meinst du so ein integriertes Modul, z.B. https://www.makershop.de/module/kommunikation-module/ttl-rs-485/ nicht den reinen Chip, oder?

Danke und Grß,
Martin

**Comment by rmeissn** [comment]
Hey Martin,

ich habe einen EasyFire 2, weswegen sich das Ganze bei dir unterscheiden könnte. Zu
1. Am Hauptbedienteil am Kessel oder am Fernbedienteil - an letzterem hängt mein ESP einfach parallel zum Bedienteil
2. Am Bedienteil ist eine Klemme mit 5 Anschlüssen (A, B, GND, VCC, Shield). Da habe ich einfach A und B abgegriffen. Ground und VCC kommen von ESP und sind nicht mit dem Bus verbunden - ich bin mir nicht sicher ob das richtig ist, scheint aber zu funktionieren. Ein separater Abschlusswiderstand war bei mir nicht gesteckt. Ggf. ist aber einer im Bedienteil integriert. Da bin ich mir auch nicht ganz sicher.
3. Genau so ein Modul habe ich bei mir im Einsatz

**Comment by marfel** [comment]
Vielen Dank Philip! Hatte nicht mehr wirklich mit einer Antwort gerechnet ;)
Ich vermute mal, das Fernbedienteil wird bei den Anlagen einigermaßen identisch sein. Mal sehen ob's klappt.
